use MetroCDMX;


ALTER TABLE `trains` DROP COLUMN `serial_number`;
ALTER TABLE `trains` ADD COLUMN `serial_number` VARCHAR(20) NOT NULL;

insert into `trains` (serial_number, line_id, type, year) values
('0JFxafE4q8', 1, 1, 1978),
('saltair007', 4, 2, 1967),
('and200the0', 2, 1, 1998),
('rust66on98', 3, 2, 1989),
('your13door', 2, 2, 1987),
('0i87never9', 4, 1, 1970),
('needed0990', 3, 1, 1963),
('anything15', 1, 2, 1998),
('013more890', 2, 2, 1989),
('17whispers', 1, 1, 1977),
('ryou20sure', 4, 1, 1997),
('never98921', 3, 2, 1991),
('72have4322', 6, 2, 1972),
('i0ever0025', 4, 2, 1993),
('Before0025', 4, 1, 1998),
('3But0I9can', 2, 2, 1974),
('See00us027', 2, 1, 1963),
('lost67in28', 1, 1, 1985),
('the5memory', 3, 2, 1959),
('7AgusT2020', 4, 2, 1960),
('19slipped0', 6, 2, 1972),
('87away0030', 2, 1, 1999),
('98into98a0', 4, 1, 1988),
('19moment89', 1, 1, 1976),
('in78time00', 2, 2, 1988);

INSERT INTO `stations` (name)
VALUES
('San Pedrito'),
('Primera Junta'),
('Puan'),
('Carabobo'),
('Acoyte'),
('Rio de Janeiro'),
('Castro Barros'),
('Loria'),
('Alberti'),
('Pasco'),
('Congreso'),
('Saenz Peña'),
('Lima'),
('Piedras'),
('Perú'),
('Plaza de Mayo'),
('Sáenz Peña'),
('Congreso'),
('Pasco'),
('Alberti'),
('Loria'),
('Castro Barros'),
('Rio de Janeiro'),
('Acoyte'),
('Primera Junta'),
('San Pedrito'),
('Juan Manuel de Rosas'),
('Echeverría'),
('Los Incas/Parque Chas'),
('Tronador'),
('Villa Ortúzar'),
('Federico Lacroze'),
('Dorrego'),
('Malabia'),
('Medrano'),
('Angel Gallardo'),
('Carlos Gardel'),
('Pueyrredón'),
('Callao'),
('Pasteur'),
('Carlos Pellegrini'),
('Florida'),
('Leandro N. Alem'),
('Catedral'),
('9 de Julio'),
('Carlos Gardel'),
('Pueyrredón'),
('Callao'),
('Pasteur'),
('Carlos Pellegrini'),
('Florida'),
('Leandro N. Alem'),
('Catedral'),
('9 de Julio'),
('Independencia'),
('Venezuela'),
('San Juan'),
('Urquiza'),
('Echeverría'),
('Juan Manuel de Rosas'),
('Constitución'),
('San Juan'),
('Independencia'),
('Moreno'),
('Avenida de Mayo'),
('Diagonal Norte'),
('Lavalle'),
('General San Martín'),
('Retiro'),
('Catalinas'),
('Correo Central'),
('Plaza de Mayo'),
('Diagonal Norte'),
('Avenida de Mayo'),
('Moreno'),
('Independencia'),
('San Juan'),
('Constitución'),
('Catedral'),
('9 de Julio'),
('Tribunales'),
('Callao'),
('Facultad de Medicina'),
('Pueyrredón'),
('Agüero'),
('Bulnes'),
('Scalabrini Ortiz'),
('Plaza Italia'),
('Palermo'),
('Ministro Carranza'),
('Olleros'),
('José Hernández'),
('Juramento'),
('Congreso de Tucumán'),
('Juramento'),
('José Hernández'),
('Olleros'),
('Ministro Carranza'),
('Palermo'),
('Plaza Italia'),
('Scalabrini Ortiz'),
('Bulnes'),
('Agüero'),
('Pueyrredón'),
('Facultad de Medicina'),
('Callao'),
('Tribunales'),
('9 de Julio'),
('Catedral'),
('Retiro'),
('Correo Central'),
('Bolívar'),
('Independencia'),
('Belgrano'),
('San José'),
('Entre');